package beans;

public class Student {	
	private int id;			// Student's ID (autogenerated by db)
	private String name;		// Student's Name
	private String password;	// Student's Password
	private String birthday;	// Student's Date of Birth
	private String email;		// Student's Email Address
	private String phone;		// Student's Phone Number
	
	/* Fully Populated Student */
	public Student(String name, String password, String birthday, String email,
			String phone) {
		this.name = name;
		this.password = password;
		this.birthday = birthday;
		this.email = email;
		this.phone = phone;
	}
	
	/* Tabla Rasa */
	public Student() {
		// Intentionally blank
	}
	
	/* New Copy */
	public Student(Student s) {
		this.id = s.getId();
		this.name = s.getName();
		this.password = s.getPassword();
		this.birthday = s.birthday;
		this.email = s.getEmail();
		this.phone = s.getPhone();
	}

	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getPassword() {
		return password;
	}
	
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getBirthday() {
		return birthday;
	}
	
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	public String getEmail() {
		return email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getPhone() {
		return phone;
	}
	
	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Override
	public String toString() {
		return "Student [birthday=" + birthday + ", email=" + email + ", id="
				+ id + ", name=" + name + ", password=" + password + ", phone="
				+ phone + "]";
	}
	
}
